module "postgresql_db" {
  source                                               = "../.."
  ibmcloud_api_key                                     = var.ibmcloud_api_key
  existing_resource_group_name                         = var.existing_resource_group_name
  prefix                                               = var.prefix
  name                                                 = var.name
  provider_visibility                                  = var.provider_visibility
  region                                               = var.region
  plan                                                 = "standard-gen2" # this is the only gen2 plan
  existing_postgresql_instance_crn                     = var.existing_postgresql_instance_crn
  postgresql_version                                   = var.postgresql_version
  remote_leader_crn                                    = null # not supported by gen2
  members                                              = var.members
  member_memory_mb                                     = var.member_memory_mb
  member_cpu_count                                     = var.member_cpu_count
  member_disk_mb                                       = var.member_disk_mb
  member_host_flavor                                   = var.member_host_flavor
  service_credential_names                             = var.service_credential_names
  admin_pass                                           = null # not supported by gen2
  users                                                = []   # not supported by gen2
  configuration                                        = null # not supported by gen2
  resource_tags                                        = var.resource_tags
  access_tags                                          = var.access_tags
  kms_encryption_enabled                               = var.kms_encryption_enabled
  existing_kms_instance_crn                            = var.existing_kms_instance_crn
  existing_kms_key_crn                                 = var.existing_kms_key_crn
  kms_endpoint_type                                    = var.kms_endpoint_type
  skip_postgresql_kms_auth_policy                      = var.skip_postgresql_kms_auth_policy
  ibmcloud_kms_api_key                                 = var.ibmcloud_kms_api_key
  key_ring_name                                        = var.key_ring_name
  key_name                                             = var.key_name
  existing_backup_kms_key_crn                          = null # not supported by gen2
  use_default_backup_encryption_key                    = false
  backup_crn                                           = null # not supported by gen2
  async_restore                                        = var.async_restore
  auto_scaling                                         = null # not supported by gen2
  existing_secrets_manager_instance_crn                = var.existing_secrets_manager_instance_crn
  existing_secrets_manager_endpoint_type               = var.existing_secrets_manager_endpoint_type
  service_credential_secrets                           = var.service_credential_secrets
  skip_postgresql_secrets_manager_auth_policy          = var.skip_postgresql_secrets_manager_auth_policy
  admin_pass_secrets_manager_secret_group              = null # not supported by gen2
  use_existing_admin_pass_secrets_manager_secret_group = null # not supported by gen2
  admin_pass_secrets_manager_secret_name               = null # not supported by gen2
  service_endpoints                                    = "private"
  deletion_protection                                  = var.deletion_protection
  version_upgrade_skip_backup                          = false
  create_timeout                                       = var.create_timeout
  update_timeout                                       = var.update_timeout
  delete_timeout                                       = var.delete_timeout
}
