---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-icd-postgresql
    kind: solution
    catalog_id: [To_be_Added]
    offering_id: [To_be_Added]
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south