name: CI-Pipeline

# Controls when the workflow will run
# Only when a comment is made
on:
  issue_comment:
    types:
     - created
     - edited

jobs:
  call-terraform-ci-pipeline:
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-terraform-module-ci.yml@v1.9.1
    secrets: inherit
    # Only run if it is a comment on a PR and its body is /run pipeline
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run pipeline' }}
    with:
      craTarget: "examples/fscloud"
      craGoalIgnoreFile: "cra-tf-validate-ignore-goals.json"
      craEnvironmentVariables: "TF_VAR_existing_at_instance_crn=crn:v1:bluemix:public:logdnaat:eu-de:a/abac0df06b644a9cabc6e44f55b3880e:b1ef3365-dfbf-4d8f-8ac8-75f4f84d6f4a::,TF_VAR_existing_kms_instance_guid=${{ vars.HPCS_SOUTH_GUID }},TF_VAR_kms_key_crn=${{ vars.HPCS_SOUTH_KEY_CRN }}"
